" --------------------------------
" ----------- 基本設定 -----------
" --------------------------------
" ステータスラインを常に表示
set laststatus=2
" 行番号を表示
set number
" 右下に表示される行・列の番号を表示する(?)
set ruler
" 不可視文字の表示
set list
set listchars=tab:▸…,trail:…,nbsp:%,extends:»,precedes:«,eol:↲
" インクリメンタルサーチ
set incsearch
" 検索結果をハイライト表示
set hlsearch
" 大文字小文字区別せずに検索
set ignorecase
" 大文字と小文字が混在した言葉で検索を行った場合に限り、大文字と小文字を区別
set smartcase
" 行頭、行末折り返し
set whichwrap=b,s,h,l,<,>,[,]
" カーソル上下の行数を確保
set scrolloff=4
" 変更中のファイルでも、保存しないで他のファイルを表示
set hidden
" コマンド、検索パターンの履歴数
set history=2048
" tabは空白を使う
set expandtab
" tabの文字数
set tabstop=2
" 行頭で<tab>でインデント
set smarttab
" <tab>で使う文字数
set shiftwidth=2
" 自動インデント
set autoindent
" 自動再読み込み
set autoread
" カーソル行強調
set cursorline
hi Cursorline cterm=NONE ctermbg=darkgray
hi CursorLineNr term=bold   cterm=NONE ctermfg=228 ctermbg=NONE
" マウス操作on
set mouse=a

" 色を変更
highlight Search ctermfg=0
highlight Visual ctermbg=8
highlight Folded ctermfg=27
highlight FoldColumn ctermfg=27
highlight DiffAdd ctermfg=0
highlight DiffChange ctermfg=0
highlight DiffDelete ctermfg=33
highlight DiffText ctermfg=0
highlight SignColumn ctermfg=27
highlight SpellBad ctermfg=0
highlight SpellCap ctermfg=0
highlight SpellRare ctermfg=0
highlight SpellLocal ctermfg=0
highlight Pmenu ctermfg=0
highlight PmenuSel ctermfg=0
highlight PmenuSbar ctermfg=0
highlight CursorColumn ctermfg=0
highlight ColorColumn ctermfg=0
highlight MatchParen ctermfg=0
highlight Ignore ctermfg=8
highlight Error ctermfg=8

" --------------------------------
" ------ NeoBundle  setting ------
" --------------------------------
if has('vim_starting')
  if &compatible
    " Be iMproved
    set nocompatible
  endif

  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!

NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make -f make_mac.mak',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }

NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neomru.vim'

" 補完機能
if has('lua')
  NeoBundleLazy 'Shougo/neocomplete.vim', {
      \ 'depends' : 'Shougo/vimproc',
      \ 'autoload' : { 'insert' : 1,}
      \ }
endif

" text整形
NeoBundleLazy 'junegunn/vim-easy-align', {
  \ 'autoload': {
  \   'commands' : ['EasyAlign'],
  \   'mappings' : ['<Plug>(EasyAlign)'],
  \ }}

" vim-easy-align {{{
" vmap <Enter> <Plug>(EasyAlign)
" nmap <Leader>a <Plug>(EasyAlign)
" " }}}

NeoBundle 'kchmck/vim-coffee-script'

NeoBundleLazy 'scrooloose/syntastic'

let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=2
let g:syntastic_mode_map = {'mode': 'passive'} 
augroup AutoSyntastic
  autocmd!
  autocmd InsertLeave,TextChanged * call s:syntastic()
augroup END
function! s:syntastic()
  w
  SyntasticCheck
endfunction

call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

